# Generated by Django 5.0.6 on 2024-07-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('degree', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('about_you', models.TextField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
