# Generated by Django 5.0.6 on 2024-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
