# Generated by Django 5.0.6 on 2024-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0002_alter_about_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
