# Generated by Django 5.0.6 on 2024-07-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0003_alter_about_address_alter_about_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
