# Generated by Django 5.0.6 on 2024-07-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0004_alter_about_address_alter_about_degree_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Yourself',
        ),
    ]
