# Generated by Django 5.0.6 on 2024-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0005_rename_about_yourself'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourself',
            name='facebook',
            field=models.CharField(default='default_facebook_value', max_length=300),
        ),
        migrations.AddField(
            model_name='yourself',
            name='linkedin',
            field=models.CharField(default='default_facebook_value', max_length=300),
        ),
        migrations.AddField(
            model_name='yourself',
            name='twitter',
            field=models.CharField(default='default_facebook_value', max_length=300),
        ),
    ]
