# Generated by Django 5.0.6 on 2024-07-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0006_yourself_facebook_yourself_linkedin_yourself_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
