# Generated by Django 5.0.6 on 2024-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayush', '0007_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourself',
            name='github',
            field=models.CharField(default='default_facebook_value', max_length=300),
        ),
    ]
